[package]
name = "hnt-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
hinata-core = { path = "../../crates/hinata-core" }
anyhow = "1.0"
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
futures-util = "0.3.31"
